# Generated by Django 5.0.6 on 2024-07-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_person_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
